/*
 * File: app/store/PESpaceDAO.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.PESpaceDAO', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.PESpace'
    ],

    config: {
        model: 'MyApp.model.PESpace',
        storeId: 'PESpaceDAO',
        proxy: {
            type: 'jsonp',
            url: 'http://54.200.11.164/parking-engine/PESpace/alljsonp',
            reader: {
                type: 'json'
            }
        }
    }
});