/*
 * File: app/view/MainViewContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewContainer', {
    extend: 'Ext.Container',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        id: 'MainViewContainer',
        ui: '',
        autoDestroy: false,
        hideOnMaskTap: false,
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'container',
                id: 'MapContainer',
                ui: '',
                autoDestroy: false,
                hideOnMaskTap: false,
                layout: {
                    type: 'fit'
                },
                modal: false,
                items: [
                    {
                        xtype: 'map',
                        id: 'MyMap',
                        itemId: 'mymap'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: 40,
                id: 'BottomToolBar',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        action: 'currentLocationButton',
                        height: 37,
                        hidden: false,
                        id: 'CurrentLocation',
                        width: 155,
                        iconCls: 'locate',
                        text: 'Current Location'
                    },
                    {
                        xtype: 'button',
                        action: 'searchLocationButtonEvent',
                        height: 37,
                        hidden: false,
                        id: 'SearchLocation',
                        width: 155,
                        iconCls: 'search',
                        text: 'Search Location'
                    },
                    {
                        xtype: 'button',
                        action: 'onPayButtonEvent',
                        hidden: true,
                        id: 'PayButton',
                        ui: 'action',
                        width: 100,
                        text: 'Pay'
                    },
                    {
                        xtype: 'button',
                        action: 'backButtonEvent',
                        hidden: true,
                        id: 'CancelButton',
                        ui: 'action',
                        width: 100,
                        text: 'Cancel'
                    }
                ]
            },
            {
                xtype: 'panel',
                action: 'addressListEvent',
                border: '',
                height: 200,
                html: '',
                id: 'SearchLocationPanel',
                hideOnMaskTap: false,
                layout: {
                    type: 'vbox'
                },
                modal: false,
                items: [
                    {
                        xtype: 'searchfield',
                        action: 'searchLocationFieldEvent',
                        border: '',
                        docked: 'top',
                        id: 'SearchLocationField',
                        itemId: 'mysearchfield',
                        label: 'From',
                        labelWidth: '20%',
                        name: '',
                        autoComplete: true
                    },
                    {
                        xtype: 'list',
                        action: 'addressListEvent',
                        height: 753,
                        id: 'AddressList',
                        itemId: 'mylist',
                        width: 899,
                        itemTpl: [
                            '<div style=\'margin-left:10px;\'>',
                            '    {formatted_address},{geo_location}',
                            '</div>'
                        ]
                    },
                    {
                        xtype: 'searchfield',
                        docked: 'top',
                        id: 'ToSearchLocationField',
                        itemId: 'mysearchfield2',
                        label: 'To',
                        labelWidth: '20%'
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'TimeSliderPanel',
                maxHeight: 30
            },
            {
                xtype: 'sliderfield',
                hidden: true,
                id: 'TimeSlider',
                maxHeight: 55,
                style: '',
                maxValue: 288
            },
            {
                xtype: 'panel',
                id: 'ToolTip',
                style: 'border-style:solid; border-top-color:#1C86EE;text-align: center; background-color:#FFFFFF; color:#1C86EE; border-radius:25px;',
                layout: {
                    align: 'start',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'label',
                        docked: 'bottom',
                        id: 'DayLabel',
                        styleHtmlContent: true
                    },
                    {
                        xtype: 'label',
                        docked: 'top',
                        id: 'TimeLabel',
                        styleHtmlContent: true
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                height: '',
                id: 'TitleToolBar',
                title: 'Valet Park',
                items: [
                    {
                        xtype: 'button',
                        action: 'backButtonEvent',
                        hidden: true,
                        id: 'BackButton',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        action: 'onTimeButtonTap',
                        hidden: true,
                        id: 'TimeButton',
                        iconCls: 'time',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        action: 'onTimeSliderButtonTap',
                        docked: 'left',
                        height: 39,
                        id: 'SliderButton',
                        ui: 'small',
                        width: 32,
                        iconCls: 'arrow_down'
                    },
                    {
                        xtype: 'button',
                        action: 'onRefreshTapEvent',
                        docked: 'left',
                        height: 37,
                        id: 'RefreshButton',
                        ui: 'small',
                        width: 37,
                        iconCls: 'refresh',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        action: 'onPayButtonScreenTap',
                        docked: 'right',
                        height: 37,
                        id: 'PayButtonScreen',
                        minWidth: 15,
                        ui: 'small',
                        width: 44,
                        iconCls: 'info',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: false,
                id: 'ParkDurationPanel',
                ui: 'dark',
                scrollable: false,
                items: [
                    {
                        xtype: 'picker',
                        bottom: 100,
                        height: 243,
                        id: 'DurationPicker',
                        ui: 'dark',
                        stretchX: true,
                        stretchY: true,
                        useTitles: true,
                        toolbar: {
                            xtype: 'toolbar',
                            docked: 'top',
                            hidden: true
                        },
                        slots: [
                            {
                                xtype: 'pickerslot',
                                id: 'HourDurationPicker',
                                itemId: 'mypickerslot9',
                                autoDestroy: false,
                                align: 'center',
                                name: 'HourPickerSlot',
                                title: 'Hours'
                            },
                            {
                                xtype: 'pickerslot',
                                id: 'MinuteDurationPicker',
                                align: 'center',
                                name: 'MinutePickerSlot',
                                title: 'Minutes'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        centered: false,
                        docked: 'bottom',
                        id: 'CVVTextField',
                        label: 'CVV',
                        labelWidth: '33%',
                        placeHolder: 'XXX'
                    },
                    {
                        xtype: 'selectfield',
                        centered: false,
                        docked: 'bottom',
                        id: 'CreditCardType',
                        label: 'Type:',
                        labelWidth: '33%',
                        options: [
                            {
                                text: 'Master Card',
                                value: 'Master Card'
                            },
                            {
                                text: 'Visa',
                                value: 'Visa'
                            },
                            {
                                text: 'American Express',
                                value: 'American Express'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        docked: 'bottom',
                        id: 'CreditCardTextField',
                        label: 'CreditCard:',
                        labelWidth: '33%',
                        placeHolder: 'XXXX XXXX XXXX XXXX'
                    },
                    {
                        xtype: 'textfield',
                        disabled: true,
                        docked: 'bottom',
                        id: 'AmountTextField',
                        label: 'Amount:',
                        labelWidth: '33%'
                    },
                    {
                        xtype: 'textfield',
                        centered: false,
                        docked: 'bottom',
                        id: 'NameTextField',
                        label: 'Name:',
                        labelWidth: '33%',
                        placeHolder: 'First & Last Name'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onSearchLocationFieldKeyup',
                buffer: 1500,
                event: 'keyup',
                delegate: '#SearchLocationField'
            },
            {
                fn: 'onAddressListSelect',
                event: 'select',
                delegate: '#AddressList'
            },
            {
                fn: 'onToSearchLocationFieldKeyup',
                event: 'keyup',
                delegate: '#ToSearchLocationField'
            }
        ]
    },

    onSearchLocationFieldKeyup: function(textfield, e, eOpts) {

        var address = textfield.getValue() + ' Sydney' + ' Australia';



        var addressArray = [];
        geoSearchForAllLocations();

        // To ensure that we have current location displayed in the list view;
        function geoSearchForAllLocations(){
            var curr = "curr";
            var Curr = "Curr";

            var fromSearchField = Ext.getCmp('SearchLocationField').getValue();
            var toSearchField = Ext.getCmp('ToSearchLocationField').getValue();

            var currfromSearchField = fromSearchField.indexOf(curr);
            var CurrfromSearchField = fromSearchField.indexOf(Curr);
            var currToSearchField = toSearchField.indexOf(curr);
            var CurrToSearchField = toSearchField.indexOf(Curr);

            var containsCurrentLocation = false;

            if((currfromSearchField != -1) || (CurrfromSearchField != -1) || (currToSearchField != -1) || (CurrToSearchField != -1)){
                containsCurrentLocation = true;
            }

            if(containsCurrentLocation){
                //This has a call back to MyApp.app.getController('MainViewController').showAddress(address,addressArray,searchFieldId);
                MyApp.app.getController('MainViewController').addCurrentLocation(address,'SearchLocationField');
            } else {
                MyApp.app.getController('MainViewController').showAddress(address,addressArray,'SearchLocationField');
            }

        }










    },

    onAddressListSelect: function(dataview, record, eOpts) {
        var searchFieldId = record.getData().search_field;
        var recordData = record.getData();
        Ext.getCmp(searchFieldId).setValue(recordData.formatted_address);

        if("SearchLocationField" === searchFieldId){
        	MyApp.app.getController('MainViewController').config.globalFromCoordinates = recordData.geo_location;
        } else {
            MyApp.app.getController('MainViewController').config.globalToCoordinates = recordData.geo_location;
        }
        MyApp.app.getController('MainViewController').clearAddressList();
    },

    onToSearchLocationFieldKeyup: function(textfield, e, eOpts) {
        var address = textfield.getValue() + ' Sydney' + ' Australia';
        var addressArray = [];
        MyApp.app.getController('MainViewController').showAddress(address,addressArray,'ToSearchLocationField');

    }

});