/*
 * File: app/view/MainViewContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewContainer', {
    extend: 'Ext.Container',

    config: {
        id: 'MainViewContainer',
        ui: '',
        autoDestroy: false,
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'TitleToolBar',
                left: '',
                minHeight: '60',
                title: 'Valet Park',
                layout: {
                    align: 'start',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        action: 'backButtonEvent',
                        hidden: true,
                        id: 'BackButton',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        action: 'onTimeButtonTap',
                        id: 'TimeButton',
                        iconCls: 'time',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'MapContainer',
                ui: '',
                autoDestroy: false,
                hideOnMaskTap: false,
                layout: {
                    type: 'fit'
                },
                modal: false,
                items: [
                    {
                        xtype: 'map',
                        id: 'MyMap',
                        itemId: 'mymap'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: 40,
                id: 'BottomToolBar',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        action: 'currentLocationButton',
                        height: 37,
                        width: 155,
                        iconCls: 'locate',
                        text: 'Current Location'
                    },
                    {
                        xtype: 'button',
                        action: 'searchLocationButtonEvent',
                        height: 37,
                        width: 155,
                        iconCls: 'search',
                        text: 'Search Location'
                    }
                ]
            },
            {
                xtype: 'panel',
                action: 'addressListEvent',
                border: '',
                html: '',
                id: 'SearchLocationPanel',
                hideOnMaskTap: false,
                modal: false,
                items: [
                    {
                        xtype: 'searchfield',
                        action: 'searchLocationFieldEvent',
                        border: '',
                        id: 'SearchLocationField',
                        itemId: 'mysearchfield',
                        label: '',
                        labelWidth: '0%',
                        name: '',
                        autoComplete: true
                    },
                    {
                        xtype: 'list',
                        action: 'addressListEvent',
                        height: 753,
                        id: 'AddressList',
                        itemId: 'mylist',
                        width: 899,
                        itemTpl: [
                            '<div style=\'margin-left:10px;\'>',
                            '    {formatted_address},{lng},{lat}',
                            '</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                docked: 'top',
                height: 250,
                hidden: true,
                id: 'TimePickerPanel',
                padding: 0,
                width: 245,
                autoDestroy: false,
                items: [
                    {
                        xtype: 'picker',
                        floatingCls: 'top',
                        height: 150,
                        hideAnimation: {
                            type: 'pop',
                            duration: 200
                        },
                        id: 'TimePicker',
                        itemId: 'mypicker',
                        padding: 0,
                        ui: '',
                        width: 245,
                        scrollable: false,
                        stretchX: true,
                        stretchY: true,
                        doneButton: {
                            iconAlign: 'right'
                        },
                        cancelButton: {
                            iconCls: 'refresh',
                            text: 'Real Time'
                        },
                        slots: [
                            {
                                xtype: 'pickerslot',
                                id: 'HourPickerSlot',
                                margin: '',
                                autoDestroy: false,
                                scrollToTopOnRefresh: false,
                                name: 'HourPickerSlot',
                                title: 'HourPickerSlot'
                            },
                            {
                                xtype: 'pickerslot',
                                id: 'MinutePickerSlot',
                                autoDestroy: false,
                                scrollToTopOnRefresh: false,
                                name: 'MinutePickerSlot',
                                title: 'MinutePickerSlot'
                            },
                            {
                                xtype: 'pickerslot',
                                id: 'AMPMPickerSlot',
                                name: 'AMPMPickerSlot',
                                title: 'AMPMPickerSlot'
                            }
                        ],
                        listeners: [
                            {
                                fn: function(component, eOpts) {

                                    var hourPickerSlot = Ext.getCmp('HourPickerSlot');
                                    var minutePickerSlot = Ext.getCmp('MinutePickerSlot');
                                    var ampmPickerSlot = Ext.getCmp('AMPMPickerSlot');

                                    var hours = MyApp.app.getController('MainViewController').createHours();
                                    var minutes = MyApp.app.getController('MainViewController').createMinutes();
                                    var ampm = MyApp.app.getController('MainViewController').createAMPM();

                                    if(!hourPickerSlot.getData()){
                                        hourPickerSlot.setData(hours);
                                    } 

                                    if(!minutePickerSlot.getData()){
                                        minutePickerSlot.setData(minutes);
                                    }

                                    if(!ampmPickerSlot.getData()){
                                        ampmPickerSlot.setData(ampm);
                                    }







                                },
                                event: 'initialize'
                            }
                        ],
                        toolbar: {
                            xtype: 'toolbar',
                            docked: 'top',
                            hidden: false,
                            id: 'TimePanelToolBar'
                        }
                    },
                    {
                        xtype: 'selectfield',
                        docked: 'bottom',
                        id: 'DayTypeSelectorField',
                        maxHeight: 100,
                        labelWidth: 0,
                        options: [
                            {
                                text: 'Weekday',
                                value: 'Weekday'
                            },
                            {
                                text: 'Saturday',
                                value: 'Saturday'
                            },
                            {
                                text: 'Sunday',
                                value: 'Sunday'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        docked: 'bottom',
                        id: 'DurationSelector',
                        maxHeight: '40%',
                        labelWidth: 0,
                        options: [
                            {
                                text: 'All',
                                value: '0'
                            },
                            {
                                text: '15 Mintues',
                                value: '0.25'
                            },
                            {
                                text: '30 Mintues',
                                value: '0.5'
                            },
                            {
                                text: '1 Hour',
                                value: '1'
                            },
                            {
                                text: '2 Hours',
                                value: '2'
                            },
                            {
                                text: '3 Hours',
                                value: '3'
                            },
                            {
                                text: '>=4 Hours',
                                value: '4'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onSearchLocationFieldKeyup',
                buffer: 1500,
                event: 'keyup',
                delegate: '#SearchLocationField'
            }
        ]
    },

    onSearchLocationFieldKeyup: function(textfield, e, eOpts) {

        var tweetStore = Ext.getStore('MyDirectStore');
        var tweetProxy = tweetStore.getProxy();
        var textFieldValue = textfield.getValue();
        var urlRequest = 'https://maps.googleapis.com/maps/api/place/textsearch/xml?query='+textFieldValue+'+Sydney&sensor=true&key=AIzaSyDh_RPGaZuLP8-bEBlIjLq98Vj91SEnaZM';
        alert(urlRequest);
        tweetProxy.setUrl(urlRequest);
        tweetStore.load();
        var addressList = Ext.getCmp("AddressList");
        addressList.refresh();
    }

});