/*
 * File: app/model/GooglePlacesApi.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.GooglePlacesApi', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'formatted_address'
            },
            {
                mapping: '',
                name: 'lat'
            },
            {
                name: 'lng'
            }
        ],
        proxy: {
            type: 'ajax',
            url: 'https://maps.googleapis.com/maps/api/place/textsearch/xml?query=syndey+Sydney&sensor=true&key=AIzaSyDh_RPGaZuLP8-bEBlIjLq98Vj91SEnaZM',
            withCredentials: true,
            reader: {
                type: 'xml',
                rootProperty: 'PlaceSearchResponse',
                record: 'result'
            }
        }
    }
});