/*
 * File: app/model/PEReport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.PEReport', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'startHour'
            },
            {
                name: 'startMinute'
            },
            {
                name: 'dayOfWeek'
            },
            {
                name: 'minEndHour'
            },
            {
                name: 'minEndMinute'
            },
            {
                name: 'maxEndHour'
            },
            {
                name: 'maxEndMinute'
            },
            {
                name: 'totalCost'
            },
            {
                name: 'totalTime'
            }
        ]
    },

    constructor: function(startTime) {
        this.callParent();
        if (startTime) {
            this.set('startHour', startTime.getHours());
            this.set('startMinute', startTime.getMinutes());
            this.set('dayOfWeek', startTime.getDay());
        }
        return this;
    },

    addToTotalCost: function(incrementTotalCost) {
        var totalCostDTO;
        if(this.get('totalCost')){
            totalCostDTO = this.get('totalCost') + incrementTotalCost;
        } else {
            totalCostDTO = incrementTotalCost;
        }
        this.set('totalCost', totalCostDTO);    

    },

    getStartTime: function() {
        return this.convertToDateTime(this.get('startHour')+ ":"+this.get('startMinute'));
    },

    getMinEndTime: function() {
        return this.convertToDateTime(this.get('minEndHour')+ ":"+this.get('minEndMinute'));
    },

    convertToDateTime: function(timeString) {
        var timeRegex = /(\d\d?):(\d\d)/;
        var today = new Date();  
        var match = timeRegex.exec(timeString);
        if(!match) return null;
        var hours = match[1]-0; 
        var minutes =  match[2]-0;
        return new Date(today.getFullYear(), today.getMonth(),today.getDay(),hours,minutes); 
    }

});