/*
 * File: app/model/PERule.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.PERule', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'fromDay'
            },
            {
                name: 'toDay'
            },
            {
                name: 'cost'
            },
            {
                name: 'fromTime'
            },
            {
                name: 'toTime'
            },
            {
                name: 'timeLimit'
            },
            {
                name: 'appliedCurrently'
            },
            {
                name: 'appliedFuture'
            },
            {
                convert: function(v, rec) {
                    return rec.get('fromTime').split(':')[0] - 0;

                },
                name: 'fromTimeHour',
                type: 'int'
            },
            {
                name: 'parkSpaceType'
            }
        ]
    },

    canBeAppliedCurrently: function(reportObject) {
        var result = false;
        var peRuleStartTime = this.getFromTime();
        var peRuleEndTime = this.getToTime();
        var reportStartTime = reportObject.getStartTime();
        var reportMinEndTime = reportObject.getMinEndTime();
        var validTimes = (peRuleStartTime && peRuleEndTime && reportStartTime);

        var validDay = this.validDay(reportObject.get('dayOfWeek'));

        //All Times
        /*
        if(reportMinEndTime === 0 && validDay){
        this.set('appliedCurrently',true);
        return true;
        }
        */

        if(validTimes && validDay){
            if((reportStartTime >= peRuleStartTime) && (reportStartTime < peRuleEndTime)){
                //alert('PE Rule can be applied');
                this.set('appliedCurrently',true);
                return true;
            }
        }



        return result;
    },

    canBeAppliedInTheFuture: function(reportObject) {
        var result = false;
        var peRuleStartTime = this.getFromTime();
        var reportStartTime = reportObject.getStartTime();
        var reportMinEndTime = reportObject.getMinEndTime();
        var validTimes = (peRuleStartTime && reportStartTime && reportMinEndTime);

        var validDay = this.validDay(reportObject.get('dayOfWeek'));


        if((reportMinEndTime === 0)&& validDay){
            this.set('appliedFuture',true);
            return true;
        }


        if(validTimes && validDay){
            if((peRuleStartTime>reportStartTime) && (reportMinEndTime>peRuleStartTime)){
                this.set('appliedFuture', true);
                return true;
            }
        }

        return result;
    },

    parseTime: function(timeString) {
        var timeRegex = /(\d\d?):(\d\d)/;
        var today = new Date();
        var match = timeRegex.exec(timeString);
        if(!match) return null;
        var hours = match[1]-0;
        var minutes =  match[2]-0;
        return new Date(today.getFullYear(), today.getMonth(),today.getDate(),hours,minutes);

    },

    getToTime: function() {
        var toTime = this.parseTime(this.get('toTime'));
        var peRep = MyApp.app.getController('MainViewController').config.globalPeReport;


        /*

        Note changing the date(dayOfMonth,Month and Year) of FROM and TO times for rules are required
        because of this.canBeAppliedCurrently/Future:

        (reportStartTime >= peRuleStartTime) && (reportStartTime < peRuleEndTime))

        The above will return false if say today is Sunday 10th Nov, we wanted to see if the Rule canBeApplied on the Sunday 17th Nov
        Since peRuleStartTime will have the peRuleStartTime && peRuleEndTime as Sunday 10th 2013, XX:XX; While reportStartTime will be Sunday 17th 2013, XX:XX

        The if statement below converts it such that peRuleStartTime will now be the same date at the Report: Sunday 17th 2013, XX:XX

        */

        if(peRep){
            var reportStartTimeDateObject = peRep.getStartTime();
            var dayOfMonth = reportStartTimeDateObject.getDate();
            var month = reportStartTimeDateObject.getMonth();
            var year = reportStartTimeDateObject.getFullYear();

            toTime.setMonth(month);
            toTime.setDate(dayOfMonth);
            toTime.setFullYear(year);
        }


        return toTime;

    },

    getFromTime: function() {
        var fromTime = this.parseTime(this.get('fromTime'));
        var peRep = MyApp.app.getController('MainViewController').config.globalPeReport;



        /*

        Note changing the date(dayOfMonth,Month and Year) of FROM and TO times for rules are required
        because of this.canBeAppliedCurrently/Future:

        (reportStartTime >= peRuleStartTime) && (reportStartTime < peRuleEndTime))

        The above will return false if say today is Sunday 10th Nov, we wanted to see if the Rule canBeApplied on the Sunday 17th Nov
        Since peRuleStartTime will have the peRuleStartTime && peRuleEndTime as Sunday 10th 2013, XX:XX; While reportStartTime will be Sunday 17th 2013, XX:XX

        The if statement below converts it such that peRuleStartTime will now be the same date at the Report: Sunday 17th 2013, XX:XX

        */

        if(peRep){
            var reportStartTimeDateObject = peRep.getStartTime();
            var dayOfMonth = reportStartTimeDateObject.getDate();
            var month = reportStartTimeDateObject.getMonth();
            var year = reportStartTimeDateObject.getFullYear();

            fromTime.setMonth(month);
            fromTime.setDate(dayOfMonth);
            fromTime.setFullYear(year);
        }


        return fromTime;

    },

    getFormattedTimeString: function(toTimeString) {
        var timeStringArray = toTimeString.split(":");
        var timeFormatted = timeStringArray[0] + ":" + timeStringArray[1];
        return timeFormatted;
    },

    validDay: function(peReportDayAsInt) {
        var validDay = false;

        var peFromDayAsInt =  MyApp.app.getController('MainViewController').convertDayStringToInt(this.get('fromDay'));
        var peToDayAsInt =  MyApp.app.getController('MainViewController').convertDayStringToInt(this.get('toDay'));

        //This just makes it easier to evaluate if valid day
        if(peReportDayAsInt===0){
            peReportDayAsInt = 7;
        }

        if (peFromDayAsInt===0){
            peFromDayAsInt = 7;
        }

        if (peToDayAsInt===0){
            peToDayAsInt = 7;
        }

        if(peReportDayAsInt>=peFromDayAsInt && peReportDayAsInt<=peToDayAsInt){
            validDay = true;
        }

        //SpecialCase for SUNDAY: Since rules will generally be written Mon-Sunday or Sat-Sunday
        //if(peReportDayAsInt===0 &&(peReportDayAsInt===peToDayAsInt)){
        //    validDay = true;
        //}

        return validDay;
    },

    getParkSpaceType: function() {
        return this.get('parkSpaceType');
    },

    getAppliedCurrently: function() {
        return this.get('appliedCurrently');
    },

    getAppliedFuture: function() {
        return this.get('appliedFuture');
    },

    getName: function() {
        var fromTime = this.getFromTime().toTimeString();
        var toTime = this.getToTime().toTimeString();
        var name = this.getFormattedTimeString(fromTime) + '-' + this.getFormattedTimeString(toTime);
        return name;
    },

    reInitRule: function() {
        this.set('appliedCurrently',false);
        this.set('appliedFuture',false);
    }

});