/*
 * File: app/model/PESpace.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.PESpace', {
    extend: 'Ext.data.Model',

    config: {
        startLat: '',
        startLng: '',
        idProperty: 'PESpace',
        fields: [
            {
                name: 'startLat'
            },
            {
                name: 'startLng'
            },
            {
                name: 'endLat'
            },
            {
                name: 'endLng'
            },
            {
                name: 'id'
            },
            {
                name: 'occupied'
            },
            {
                name: 'ruleIds'
            }
        ]
    },

    constructor: function(config) {
        this.initConfig(config);
        var me = this;
        me.callParent([config]);

        /* How to Initialize This Model If Required:
        var peSpace = new MyApp.model.PESpace({
        id: id,
        startLat: startLat,
        startLng: startLng,
        endLat: endLat,
        endLng: endLng
        });

        */
    }

});